#pragma once

#include "gpu_rsqrt.h"

// ============================================================
// Rsqrt Keygen (GPU)
//
// Protocol:
//   1. F2BF16: converts variance (scalar per row) to 13-bit
//      floating-point index — output mask stays on GPU.
//   2. LUT keygen: generates DPF key for the invSqrt table
//      lookup, using the F2BF16 output mask as input mask.
//
// d_mask_X: GPU pointer, N elements (SumSq masks from variance)
// Returns:  GPU pointer, N elements (invSqrt output mask)
// ============================================================
template <typename T>
T *gpuFssKeyGenRsqrt(u8 **key_as_bytes, int party,
                      int bw, int bin, int scale, int N,
                      T *d_mask_X,           // GPU pointer
                      AESGlobalContext *gaes)
{
    // Step 1: F2BF16 keygen — input and output both on GPU
    // Returns 13-bit index mask (GPU pointer, N elements)
    T *d_mask_f2bf16 = gpuFssKeyGenF2BF16<T>(
        key_as_bytes, party, bin, N, d_mask_X, gaes);

    // Step 2: LUT keygen for invSqrt
    // gpuKeyGenLUT expects a GPU pointer for d_rin — d_mask_f2bf16 qualifies
    // bin=13 (index width), bout=bw (output width matching the softmax ring)
    T *d_mask_lut = gpuKeyGenLUT<T, T>(
        key_as_bytes, party, 13, bw, N, d_mask_f2bf16, gaes);

    gpuFree(d_mask_f2bf16);

    return d_mask_lut;   // GPU pointer, caller uses writeShares or passes forward
}

// ============================================================
// Rsqrt Evaluator (GPU)
//
// Protocol:
//   1. F2BF16: converts public masked variance → 13-bit LUT index
//      (GPU pointer, both parties produce shares that reconstruct
//       to the same index — verified inside gpuFssF2BF16)
//   2. LUT eval: gpuDpfLUT looks up invSqrt table at that index
//
// d_x:     GPU pointer, N elements (public masked SumSq values,
//          already fully reconstructed by caller before this call)
// d_tab:   GPU pointer, 2^13 elements (invSqrt LUT, generated by
//          genLUT<T, invSqrt<T>>(13, extradiv, scale) on GPU)
// Returns: GPU pointer, N elements (invSqrt output share)
// ============================================================
template <typename T>
T *gpuFssRsqrt(SigmaPeer *peer, int party,
               T *d_x, T *d_tab, int N,
               GpuFssRsqrtKey<T> &k,
               int bw, AESGlobalContext *gaes, Stats *s,
               int OpType = 0)
{
    // Step 1: F2BF16 — d_x is already fully public (reconstructed
    // by the caller via reconstructInPlace on SumSq). gpuFssF2BF16
    // internally runs the 4-round MPC protocol and returns a GPU
    // pointer holding this party's 13-bit index share.
    T *d_f2bf16 = gpuFssF2BF16<T>(
        peer, party, d_x, k.f2bf16Key, gaes, s, OpType);

    // Step 2: LUT lookup for invSqrt
    // gpuDpfLUT handles its own network rounds internally
    T *d_result = gpuDpfLUT<T, T>(
        k.lutKey, peer, party, d_f2bf16, d_tab, gaes, s, true, OpType);

    gpuFree(d_f2bf16);

    return d_result;
}
